# Generated by Django 3.2.10 on 2021-12-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebit_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bit',
            options={'verbose_name_plural': 'Bits'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name_plural': 'Bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='friendship',
            options={'verbose_name_plural': 'Friendships'},
        ),
        migrations.AlterModelOptions(
            name='friendshipstatus',
            options={'verbose_name_plural': 'Friendship Status'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name_plural': 'Likes'},
        ),
    ]
