# Generated by Django 3.2.10 on 2021-12-29 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firebit_api', '0002_auto_20211227_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bit',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Bits'},
        ),
        migrations.CreateModel(
            name='UserThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('content_type', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('auth_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Thumbnails',
            },
        ),
    ]
