# Generated by Django 3.2.10 on 2022-01-13 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firebit_api', '0003_auto_20220113_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friendship_status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='firebit_api.friendshipstatus'),
        ),
    ]
