# Generated by Django 3.2.10 on 2022-01-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firebit_api', '0005_comment_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='bit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebit_api.bit'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='bit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebit_api.bit'),
        ),
        migrations.AlterField(
            model_name='image',
            name='bit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebit_api.bit'),
        ),
        migrations.AlterField(
            model_name='like',
            name='bit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firebit_api.bit'),
        ),
    ]
