# Generated by Django 3.2.10 on 2022-01-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebit_api', '0008_auto_20220119_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='path',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
