# Generated by Django 3.2.10 on 2022-01-21 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firebit_api', '0009_auto_20220120_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
