# Generated by Django 3.2.10 on 2022-01-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebit_api', '0014_delete_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
